<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Message;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new ClassMetadata(Message::class));
    }

    public function getUserOutbox(int $userId){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT m FROM AppBundle:Message m 
                                        WHERE m.sender = $userId");
        return $query->getResult();
    }

    public function getUserInbox(int $userId){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT m FROM AppBundle:Message m 
                                        WHERE m.receiver = $userId
                                        ORDER BY m.sendDate DESC");
        return $query->getResult();
    }
}
