<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;
use AppBundle\Entity\PostLike;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * PostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(PostLike::class));
    }

    public function isLiked(Post $post,User $user): bool{
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(l) as c FROM AppBundle:PostLike l
                                        WHERE l.user = :u
                                        AND l.post = :p');
        $query->setParameter('u',$user);
        $query->setParameter('p',$post);

        $res = $query->getArrayResult();
        $res = array_shift($res[0]);

        if (intval($res) !== 0){
            return true;
        }

        return false;
    }
}
