<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Post::class));
    }

    public function getAll(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p,o FROM AppBundle:Post p
                                        JOIN p.owner o');
        return $query->getResult();
    }

    public function getFollowedPosts(User $user){
        $friends = [];
        foreach ($user->getFriends() as $friend){
            $friends[] = $friend;
        }
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p,o
                                        FROM AppBundle:Post p
                                        JOIN p.owner o
                                        WHERE o IN (:ufr)
                                        ORDER BY p.postDate DESC");
        $query->setParameter('ufr',$friends);
        return $query->getResult();
    }
}
