<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new ClassMetadata(User::class));
    }

    public function findByUsername(string $username){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM AppBundle:User u 
                                        WHERE u.username = :username
                                        OR CONCAT(u.firstName,' ',u.lastName) = :username
                                        OR u.firstName = :username
                                        OR u.lastName = :username");
        $query->setParameter('username',$username);
        return $query->getResult();
    }

}
