# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
          AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true

            form_login:
                check_path: login
                login_path: login
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: logout
                target: homepage
